Repository softeerbootcamp4th/Team5-WatermelonClap-FE, pull requests merged in 2024-08, with the labels that each got.

#38 feat(CLAP-121): 메인페이지 타이머 애니메이션
  packages/service/package.json
  packages/service/src/components/main/EventPeriod/EventPeriod.tsx
  packages/service/src/components/main/EventPeriod/Timer/Timer.tsx
  packages/service/src/components/main/EventPeriod/Timer/index.ts
  packages/service/src/components/main/EventPeriod/Timer/style.ts
  packages/service/src/components/main/EventPeriod/Timer/type.ts
  packages/service/src/components/main/EventPeriod/index.ts
  packages/service/src/components/main/EventPeriod/style.ts
  packages/service/src/pages/Main/style.ts
  pnpm-lock.yaml
Labels: ✨ feat

#36 feat(CLAP-75): Footer 컴포넌트 구현
  packages/service/src/common/components/Footer/Footer.css.ts
  packages/service/src/common/components/Footer/Footer.tsx
Labels: ✨ feat

#37 feat(CLAP-78): CheckBox 컴포넌트 구현
  packages/service/src/Demo/pages/ButtonDemoPage.tsx
  packages/service/src/common/components/CheckBox/CheckBox.css.ts
  packages/service/src/common/components/CheckBox/CheckBox.tsx
  packages/service/src/common/components/CheckBox/index.ts
Labels: ✨ feat

#40 feat(CLAP-92): 구글 로그인 모달 && Modal Provider 구현
  packages/service/index.html
  packages/service/package.json
  packages/service/src/Demo/pages/DemoPage.tsx
  packages/service/src/Demo/pages/ModalDemoPage.tsx
  packages/service/src/common/components/ModalContainer/GoolgleLoginModal/GoogleLoginModal.css.ts
  packages/service/src/common/components/ModalContainer/GoolgleLoginModal/GoogleLoginModal.tsx
  packages/service/src/common/components/ModalContainer/GoolgleLoginModal/index.ts
  packages/service/src/common/components/ModalContainer/ModalContainer.tsx
  packages/service/src/common/components/ModalContainer/index.ts
  packages/service/src/common/contexts/ModalContext.ts
  packages/service/src/common/hooks/useModal.ts
  packages/service/src/common/hooks/useScrollStop.ts
  packages/service/src/common/providers/ModalProvider.tsx
  packages/service/src/constants/routes.ts
  packages/service/src/index.tsx
  packages/service/src/router.tsx
  pnpm-lock.yaml
Labels: ✨ feat

#39 feat(CLAP-82): 메인페이지 기대평 구현
  packages/service/src/common/components/Marquee/Marquee.css.ts
  packages/service/src/common/components/Marquee/Marquee.tsx
  packages/service/src/components/main/Expectation/Expectations.tsx
  packages/service/src/components/main/Expectation/index.ts
  packages/service/src/components/main/Expectation/style.ts
  packages/service/src/components/main/index.ts
  packages/service/src/pages/Main/Main.tsx
Labels: ✨ feat

#42 feat(CLAP-72): 공통 컴포넌트 구현
  packages/service/index.html
  packages/service/package.json
  packages/service/src/Demo/pages/ButtonDemoPage.tsx
  packages/service/src/Demo/pages/DemoPage.tsx
  packages/service/src/Demo/pages/ModalDemoPage.tsx
  packages/service/src/common/components/CheckBox/CheckBox.css.ts
  packages/service/src/common/components/CheckBox/CheckBox.tsx
  packages/service/src/common/components/CheckBox/index.ts
  packages/service/src/common/components/Footer/Footer.css.ts
  packages/service/src/common/components/Footer/Footer.tsx
  packages/service/src/common/components/ModalContainer/GoolgleLoginModal/GoogleLoginModal.css.ts
  packages/service/src/common/components/ModalContainer/GoolgleLoginModal/GoogleLoginModal.tsx
  packages/service/src/common/components/ModalContainer/GoolgleLoginModal/index.ts
  packages/service/src/common/components/ModalContainer/ModalContainer.tsx
  packages/service/src/common/components/ModalContainer/index.ts
  packages/service/src/common/contexts/ModalContext.ts
  packages/service/src/common/hooks/useModal.ts
  packages/service/src/common/hooks/useScrollStop.ts
  packages/service/src/common/providers/ModalProvider.tsx
  packages/service/src/constants/routes.ts
  packages/service/src/index.tsx
  packages/service/src/router.tsx
  pnpm-lock.yaml
Labels: ✨ feat

#44 chore(CLAP-123): 메인페이지 타이머 디자인 수정
  packages/service/src/components/main/EventPeriod/Timer/Timer.tsx
  packages/service/src/components/main/EventPeriod/Timer/style.ts
Labels: 🍉 chore

#46 docs: pr 템플릿 수정
  .github/pull_request_template.md
Labels: 📄 docs

#47 feat(CLAP-126): 모바일 반응형 미디어쿼리 함수화
  packages/service/src/common/responsive/responsive.ts
Labels: ✨ feat

#45 chore(CLAP-124): theme depth 줄이기 및 baseStyle과 theme 통합
  packages/core/src/theme/baseStyles.ts
  packages/core/src/theme/globalStyles.ts
  packages/core/src/theme/index.ts
  packages/core/src/theme/theme.ts
  packages/service/src/Demo/pages/ButtonDemoPage.tsx
  packages/service/src/common/components/Button/Button.css.ts
  packages/service/src/common/components/CheckBox/CheckBox.css.ts
  packages/service/src/common/components/ClipBoardButton/ClipBoardButton.css.ts
  packages/service/src/common/components/Footer/Footer.css.ts
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavigationBar.css.ts
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavs.css.ts
  packages/service/src/common/components/ModalContainer/GoolgleLoginModal/GoogleLoginModal.css.ts
  packages/service/src/common/components/ModalContainer/GoolgleLoginModal/GoogleLoginModal.tsx
  packages/service/src/components/main/Banner/Banner.tsx
  packages/service/src/index.tsx
Labels: 🍉 chore

#48 feat(CLAP-87): 퀴즈 섹션 컴포넌트 구현
  packages/service/public/images/quiz/nQuizBackground.png
  packages/service/public/images/quiz/quiz1.svg
  packages/service/public/images/quiz/reward1.svg
  packages/service/public/images/quiz/reward2.svg
  packages/service/public/images/quiz/reward3.svg
  packages/service/public/images/quiz/reward4.svg
  packages/service/public/images/quiz/reward5.svg
  packages/service/src/components/nQuizEvent/NQuizHeader/NQuizHeader.css.ts
  packages/service/src/components/nQuizEvent/NQuizHeader/NQuizHeader.tsx
  packages/service/src/components/nQuizEvent/NQuizHeader/index.ts
  packages/service/src/components/nQuizEvent/NQuizInput/NQuizInput.css.ts
  packages/service/src/components/nQuizEvent/NQuizInput/NQuizInput.tsx
  packages/service/src/components/nQuizEvent/NQuizInput/index.ts
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizSection.css.ts
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizSection.tsx
  packages/service/src/components/nQuizEvent/NQuizSection/index.ts
  packages/service/src/components/nQuizEvent/index.ts
Labels: ✨ feat

#50 feat(CLAP-85): 이벤트소개 헤더 구현
  packages/service/src/components/nQuizEvent/NQuizTitle/NQuizTitle.css.ts
  packages/service/src/components/nQuizEvent/NQuizTitle/NQuizTitle.tsx
  packages/service/src/components/nQuizEvent/NQuizTitle/index.ts
  packages/service/src/components/nQuizEvent/index.ts
Labels: ✨ feat

#49 feat(CLAP-86): NQuizReward 컴포넌트 구현
  packages/service/src/components/nQuizEvent/NQuizReward/NQuizReward.css.ts
  packages/service/src/components/nQuizEvent/NQuizReward/NQuizReward.tsx
  packages/service/src/components/nQuizEvent/NQuizReward/index.ts
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizHeader/NQuizHeader.css.ts
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizHeader/NQuizHeader.tsx
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizHeader/index.ts
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizInput/NQuizInput.css.ts
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizInput/NQuizInput.tsx
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizInput/index.ts
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizSection.tsx
Labels: ✨ feat

#53 feat(CLAP-125): 메인 페이지 컴포넌트들 반응형 구현
  .github/pull_request_template.md
  packages/core/src/theme/theme.ts
  packages/service/package.json
  packages/service/src/common/components/Button/Button.tsx
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavigationBar.css.ts
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavigationBar.tsx
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavs.css.ts
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/GlobalNavs.css.ts
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/GlobalNavs.tsx
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/index.ts
  packages/service/src/common/components/GlobalNavigationBar/MenuButton/MenuButton.tsx
  packages/service/src/common/components/GlobalNavigationBar/MenuButton/index.ts
  packages/service/src/common/components/GlobalNavigationBar/index.ts
  packages/service/src/common/hooks/useMobile.ts
  packages/service/src/common/responsive/responsive.ts
  packages/service/src/components/main/Banner/Banner.css.ts
  packages/service/src/components/main/Banner/Banner.tsx
  packages/service/src/components/main/Banner/style.ts
  packages/service/src/components/main/EventCard/EventCard.css.ts
  packages/service/src/components/main/EventCard/EventCard.tsx
  packages/service/src/components/main/EventPeriod/EventPeriod.css.ts
  packages/service/src/components/main/EventPeriod/EventPeriod.tsx
  packages/service/src/components/main/EventPeriod/Timer/Timer.css.ts
  packages/service/src/components/main/EventPeriod/Timer/Timer.tsx
  packages/service/src/components/main/EventPeriod/style.ts
  packages/service/src/components/main/Expectation/Expectations.css.ts
  packages/service/src/components/main/Expectation/Expectations.tsx
  packages/service/src/constants/breakpoints.ts
  packages/service/src/pages/Main/Main.css.ts
  packages/service/src/pages/Main/Main.tsx
  packages/service/src/pages/Main/style.ts
  pnpm-lock.yaml
Labels: ✨ feat

#54 feat(CLAP-128): 공통 모달 만들기
  packages/service/src/common/components/ModalContainer/AlertModal/AlertModal.css.ts
  packages/service/src/common/components/ModalContainer/AlertModal/AlertModal.tsx
  packages/service/src/common/components/ModalContainer/AlertModal/index.ts
  packages/service/src/common/components/ModalContainer/GoolgleLoginModal/GoogleLoginModal.tsx
  packages/service/src/common/components/ModalContainer/ModalContainer.tsx
Labels: ✨ feat

#51 feat(CLAP-127): GNB 반응형 구현
  packages/service/package.json
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavigationBar.css.ts
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavigationBar.tsx
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavs.css.ts
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/GlobalNavs.css.ts
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/GlobalNavs.tsx
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/index.ts
  packages/service/src/common/components/GlobalNavigationBar/MenuButton/MenuButton.tsx
  packages/service/src/common/components/GlobalNavigationBar/MenuButton/index.ts
  packages/service/src/common/components/GlobalNavigationBar/index.ts
  packages/service/src/common/hooks/useMobile.ts
  packages/service/src/common/responsive/responsive.ts
  packages/service/src/constants/breakpoints.ts
  pnpm-lock.yaml
Labels: ✨ feat

#52 feat(CLAP-110): 아반떼 N퀴즈 이벤트 페이지 구현
  packages/service/public/images/quiz/nQuizBackground.png
  packages/service/public/images/quiz/quiz1.svg
  packages/service/public/images/quiz/reward1.svg
  packages/service/public/images/quiz/reward2.svg
  packages/service/public/images/quiz/reward3.svg
  packages/service/public/images/quiz/reward4.svg
  packages/service/public/images/quiz/reward5.svg
  packages/service/src/common/components/Footer/Footer.css.ts
  packages/service/src/components/nQuizEvent/NQuizReward/NQuizReward.css.ts
  packages/service/src/components/nQuizEvent/NQuizReward/NQuizReward.tsx
  packages/service/src/components/nQuizEvent/NQuizReward/index.ts
  packages/service/src/components/nQuizEvent/NQuizReward/type.ts
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizAlternativeBody/NQuizAlternativeBody.css.ts
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizAlternativeBody/NQuizAlternativeBody.tsx
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizAlternativeBody/index.ts
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizHeader/NQuizHeader.css.ts
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizHeader/NQuizHeader.tsx
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizHeader/index.ts
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizInput/NQuizInput.css.ts
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizInput/NQuizInput.tsx
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizInput/index.ts
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizSection.css.ts
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizSection.tsx
  packages/service/src/components/nQuizEvent/NQuizSection/index.ts
  packages/service/src/components/nQuizEvent/NQuizTitle/NQuizTitle.css.ts
  packages/service/src/components/nQuizEvent/NQuizTitle/NQuizTitle.tsx
  packages/service/src/components/nQuizEvent/NQuizTitle/index.ts
  packages/service/src/components/nQuizEvent/index.ts
  packages/service/src/constants/routes.ts
  packages/service/src/constants/terms.ts
  packages/service/src/pages/NQuizEvent/NQuizEvent.css.ts
  packages/service/src/pages/NQuizEvent/NQuizEvent.tsx
  packages/service/src/pages/NQuizEvent/index.ts
  packages/service/src/router.tsx
Labels: ✨ feat

#57 chore: NewCarInfo 내부의 useElementViewportPosition 을 hooks 폴더로 분리
  packages/service/src/common/hooks/useElementViewportPosition.ts
  packages/service/src/components/newCar/NewCarInfo/NewCarInfo.tsx
Labels: 🍉 chore

#58 hotfix: 신차소개 페이지 배경에 원 이미지가 레이어 앞쪽에 돌출되던 이슈 해결
  packages/service/public/images/common/bg-circle-blue.svg
  packages/service/public/images/common/bg-circle-green.svg
  packages/service/src/components/newCar/NewCarInfo/NewCarInfo.css.ts
  packages/service/src/components/newCar/NewCarInfo/NewCarInfo.tsx
Labels: 🔧 hotfix

#64 feat(CLAP-112): 카드 뽑기 페이지 만들기
  packages/service/package.json
  packages/service/public/images/parts/back.svg
  packages/service/public/images/parts/background.svg
  packages/service/public/images/parts/front.svg
  packages/service/public/images/parts/holo.svg
  packages/service/src/common/utils/confettiCrafter.ts
  packages/service/src/components/partsPick/PartsCard/PartsCard.css.ts
  packages/service/src/components/partsPick/PartsCard/PartsCard.tsx
  packages/service/src/components/partsPick/PartsCard/index.ts
  packages/service/src/components/partsPick/PickTitle/PickTitle.css.ts
  packages/service/src/components/partsPick/PickTitle/PickTitle.tsx
  packages/service/src/components/partsPick/PickTitle/index.ts
  packages/service/src/components/partsPick/index.ts
  packages/service/src/constants/routes.ts
  packages/service/src/pages/PartsPick/PartsPick.css.ts
  packages/service/src/pages/PartsPick/PartsPick.tsx
  packages/service/src/pages/PartsPick/index.ts
  packages/service/src/router.tsx
  pnpm-lock.yaml
Labels: ✨ feat

#62 feat(CLAP-111): 카드뽑기 이벤트 페이지 구현 중
  packages/service/package.json
  packages/service/public/images/pickEvent/card/card-1.svg
  packages/service/public/images/pickEvent/card/card-2.svg
  packages/service/public/images/pickEvent/card/card-3.svg
  packages/service/public/images/pickEvent/card/card-4.svg
  packages/service/public/images/pickEvent/card/card-5.svg
  packages/service/public/images/pickEvent/card/card-6.svg
  packages/service/public/images/pickEvent/card/card-7.svg
  packages/service/public/images/pickEvent/joinInfo/arrow.svg
  packages/service/public/images/pickEvent/joinInfo/join-info-1.svg
  packages/service/public/images/pickEvent/joinInfo/join-info-2.svg
  packages/service/public/images/pickEvent/joinInfo/join-info-3.svg
  packages/service/public/images/pickEvent/joinInfo/join-info-4.svg
  packages/service/public/images/pickEvent/joinInfo/join-info-5.svg
  packages/service/src/components/pickEvent/CardCarousel/CardCarousel.css.ts
  packages/service/src/components/pickEvent/CardCarousel/CardCarousel.tsx
  packages/service/src/components/pickEvent/CardCarousel/index.ts
  packages/service/src/components/pickEvent/JoinInfo/JoinInfo.css.ts
  packages/service/src/components/pickEvent/JoinInfo/JoinInfo.tsx
  packages/service/src/components/pickEvent/JoinInfo/index.ts
  packages/service/src/components/pickEvent/index.ts
  packages/service/src/pages/PickEvent/PickEvent.css.ts
  packages/service/src/pages/PickEvent/PickEvent.tsx
  packages/service/src/router.tsx
  pnpm-lock.yaml
Labels: ✨ feat

#63 feat(CLAP-130): 신차소개 페이지 카 트레이서 구현
  packages/service/public/images/newCar/tracingCar.svg
  packages/service/src/components/newCar/NewCarInfo/NewCarInfo.css.ts
  packages/service/src/components/newCar/NewCarInfo/NewCarInfo.tsx
  packages/service/src/components/newCar/TracingCar/TracingCar.css.ts
  packages/service/src/components/newCar/TracingCar/TracingCar.tsx
  packages/service/src/components/newCar/TracingCar/index.ts
  packages/service/src/components/newCar/util/pathGenerator.ts
Labels: ✨ feat

#65 hotfix: 모바일 뷰 깨짐 현상 수정
  packages/service/src/common/components/Button/Button.tsx
  packages/service/src/common/components/Button/index.ts
  packages/service/src/common/components/Footer/Footer.css.ts
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/GlobalNavs.tsx
  packages/service/src/common/components/ModalContainer/AlertModal/AlertModal.css.ts
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizSection.css.ts
  packages/service/src/constants/routes.ts
  packages/service/src/pages/NQuizEvent/NQuizEvent.tsx
  packages/service/src/pages/PartsPick/PartsPick.tsx
  packages/service/src/router.tsx
Labels: 🔧 hotfix

#66 feat(CLAP-93): [PickEvnet 페이지] 경품 안내 컴포넌트 구현
  packages/service/public/images/pickEvent/prize/prize-1.svg
  packages/service/public/images/pickEvent/prize/prize-2.svg
  packages/service/public/images/pickEvent/prize/prize-3.svg
  packages/service/public/images/pickEvent/prize/prize-4.svg
  packages/service/public/images/pickEvent/prize/prize-5.svg
  packages/service/public/images/pickEvent/prize/prize-mini.svg
  packages/service/src/components/pickEvent/PrizeContainer/PrizeContainer.css.ts
  packages/service/src/components/pickEvent/PrizeContainer/PrizeContainer.tsx
  packages/service/src/components/pickEvent/PrizeContainer/PrizeItem/PrizeItem.css.ts
  packages/service/src/components/pickEvent/PrizeContainer/PrizeItem/PrizeItem.tsx
  packages/service/src/components/pickEvent/PrizeContainer/PrizeItem/index.ts
  packages/service/src/components/pickEvent/PrizeContainer/data.ts
  packages/service/src/components/pickEvent/PrizeContainer/index.ts
  packages/service/src/components/pickEvent/index.ts
  packages/service/src/constants/breakpoints.ts
  packages/service/src/pages/PickEvent/PickEvent.tsx
Labels: ✨ feat

#67 feat(CLAP-111): 파츠 뽑기 이벤트 소개 페이지 구현
  packages/service/public/images/pickEvent/prize/prize-1.svg
  packages/service/public/images/pickEvent/prize/prize-2.svg
  packages/service/public/images/pickEvent/prize/prize-3.svg
  packages/service/public/images/pickEvent/prize/prize-4.svg
  packages/service/public/images/pickEvent/prize/prize-5.svg
  packages/service/public/images/pickEvent/prize/prize-mini.svg
  packages/service/src/components/pickEvent/PrizeContainer/PrizeContainer.css.ts
  packages/service/src/components/pickEvent/PrizeContainer/PrizeContainer.tsx
  packages/service/src/components/pickEvent/PrizeContainer/PrizeItem/PrizeItem.css.ts
  packages/service/src/components/pickEvent/PrizeContainer/PrizeItem/PrizeItem.tsx
  packages/service/src/components/pickEvent/PrizeContainer/PrizeItem/index.ts
  packages/service/src/components/pickEvent/PrizeContainer/data.ts
  packages/service/src/components/pickEvent/PrizeContainer/index.ts
  packages/service/src/components/pickEvent/index.ts
  packages/service/src/constants/breakpoints.ts
  packages/service/src/constants/terms.ts
  packages/service/src/pages/PickEvent/PickEvent.css.ts
  packages/service/src/pages/PickEvent/PickEvent.tsx
Labels: ✨ feat

#69 hotfix: 모바일 뷰 오류 수정
  packages/service/src/components/newCar/NewCarInfo/NewCarInfo.css.ts
  packages/service/src/pages/NQuizEvent/NQuizEvent.css.ts
Labels: 🔧 hotfix

#71 chore(CLAP-132): 퀴즈페이지 모바일 뷰 수정
  packages/service/src/components/nQuizEvent/NQuizReward/NQuizReward.css.ts
  packages/service/src/components/nQuizEvent/NQuizTitle/NQuizTitle.css.ts
  packages/service/src/pages/NQuizEvent/NQuizEvent.css.ts
  packages/service/src/pages/NQuizEvent/NQuizEvent.tsx
Labels: 🍉 chore

#73 feat(CLAP-137): Suspense, ErrorBoundary 구성
  packages/service/package.json
  packages/service/src/App.tsx
  packages/service/src/common/utils/customFetch.ts
  packages/service/src/index.tsx
  packages/service/src/pages/Error/Error.css.ts
  packages/service/src/pages/Error/Error.tsx
  packages/service/src/pages/Error/index.ts
  packages/service/src/pages/Loading/Loading.css.ts
  packages/service/src/pages/Loading/Loading.tsx
  packages/service/src/pages/Loading/index.ts
  pnpm-lock.yaml
Labels: ✨ feat

#72 feat(CLAP-100): [PartsCollection 페이지] 커스텀카드 구현
  packages/service/public/images/partsCollection/defaultCar.svg
  packages/service/src/components/partsCollection/CustomCard/CustomCard.css.ts
  packages/service/src/components/partsCollection/CustomCard/CustomCard.tsx
  packages/service/src/components/partsCollection/CustomCard/index.ts
  packages/service/src/components/partsCollection/index.ts
  packages/service/src/pages/PartsCollection/PartsCollection.css.ts
  packages/service/src/pages/PartsCollection/PartsCollection.tsx
Labels: ✨ feat

#70 feat(CLAP-134): parts-pick 페이지 API 연동
  .github/workflows/fb-hosting-service-merge.yml
  packages/service/src/Demo/pages/AuthDemoPage.tsx
  packages/service/src/apis/partsEvent/apiGetPartsRemain.ts
  packages/service/src/apis/partsEvent/apiPostParts.ts
  packages/service/src/apis/partsEvent/index.ts
  packages/service/src/apis/partsEvent/type.ts
  packages/service/src/common/hooks/useAuth.ts
  packages/service/src/common/utils/getAccessToken.ts
  packages/service/src/common/utils/index.ts
  packages/service/src/components/main/EventCard/EventCard.css.ts
  packages/service/src/components/partsPick/PartsCard/PartsCard.tsx
  packages/service/src/components/pickEvent/CardCarousel/CardCarousel.tsx
  packages/service/src/index.tsx
  packages/service/src/pages/PartsPick/PartsPick.tsx
  packages/service/src/pages/PickEvent/PickEvent.tsx
Labels: ✨ feat

#74 feat(CLAP-133): 선착순 이벤트 API 연동
  packages/service/public/images/modal/pending.gif
  packages/service/src/apis/orderEvent/apiGetOrderEvent.ts
  packages/service/src/apis/orderEvent/apiPostOrderEvent.ts
  packages/service/src/apis/orderEvent/index.ts
  packages/service/src/apis/orderEvent/type.ts
  packages/service/src/common/components/ModalContainer/ModalContainer.tsx
  packages/service/src/common/components/ModalContainer/content/modalContent.tsx
  packages/service/src/common/components/ModalContainer/index.ts
  packages/service/src/common/components/ModalContainer/modal/AlertModal/AlertModal.css.ts
  packages/service/src/common/components/ModalContainer/modal/AlertModal/AlertModal.tsx
  packages/service/src/common/components/ModalContainer/modal/AlertModal/index.ts
  packages/service/src/common/components/ModalContainer/modal/GoolgleLoginModal/GoogleLoginModal.css.ts
  packages/service/src/common/components/ModalContainer/modal/GoolgleLoginModal/GoogleLoginModal.tsx
  packages/service/src/common/components/ModalContainer/modal/GoolgleLoginModal/index.ts
  packages/service/src/common/components/ModalContainer/modal/NavigateModal/NavigateModal.css.ts
  packages/service/src/common/components/ModalContainer/modal/NavigateModal/NavigateModal.tsx
  packages/service/src/common/components/ModalContainer/modal/NavigateModal/index.ts
  packages/service/src/common/components/ModalContainer/modal/PendingModal/PendingModal.css.ts
  packages/service/src/common/components/ModalContainer/modal/PendingModal/PendingModal.tsx
  packages/service/src/common/components/ModalContainer/modal/PendingModal/index.ts
  packages/service/src/common/components/ModalContainer/modal/index.ts
  packages/service/src/components/nQuizEvent/NQuizReward/NQuizReward.css.ts
  packages/service/src/components/nQuizEvent/NQuizReward/NQuizReward.tsx
  packages/service/src/components/nQuizEvent/NQuizReward/type.ts
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizAlternativeBody/NQuizAlternativeBody.css.ts
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizAlternativeBody/NQuizAlternativeBody.tsx
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizHeader/NQuizHeader.tsx
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizInput/NQuizInput.tsx
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizSection.css.ts
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizSection.tsx
  packages/service/src/pages/NQuizEvent/NQuizEvent.tsx
Labels: ✨ feat

#77 feat(CLAP-113): 파츠컬렉션 페이지 구현
  packages/core/src/hooks/useAuth.ts
  packages/core/src/types/partsEvent/index.ts
  packages/core/src/utils/getAccessToken.ts
  packages/service/package.json
  packages/service/public/images/partsCollection/defaultCar.svg
  packages/service/src/apis/partsEvent/apiGetMyParts.ts
  packages/service/src/apis/partsEvent/apiPatchMyParts.ts
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/GlobalNavs.tsx
  packages/service/src/components/main/EventCard/EventCard.tsx
  packages/service/src/components/partsCollection/CustomCard/CustomCard.css.ts
  packages/service/src/components/partsCollection/CustomCard/CustomCard.tsx
  packages/service/src/components/partsCollection/CustomCard/index.ts
  packages/service/src/components/partsCollection/PartsTab/PartsCard/PartsCard.css.ts
  packages/service/src/components/partsCollection/PartsTab/PartsCard/PartsCard.tsx
  packages/service/src/components/partsCollection/PartsTab/PartsCard/index.ts
  packages/service/src/components/partsCollection/PartsTab/PartsTab.css.ts
  packages/service/src/components/partsCollection/PartsTab/PartsTab.tsx
  packages/service/src/components/partsCollection/PartsTab/index.ts
  packages/service/src/components/partsCollection/index.ts
  packages/service/src/components/partsPick/PartsCard/PartsCard.tsx
  packages/service/src/constants/routes.ts
  packages/service/src/index.css
  packages/service/src/index.tsx
  packages/service/src/pages/Main/index.ts
  packages/service/src/pages/NewCar/NewCar.tsx
  packages/service/src/pages/PartsCollection/PartsCollection.css.ts
  packages/service/src/pages/PartsCollection/PartsCollection.tsx
  packages/service/src/pages/PartsCollection/index.ts
  packages/service/src/pages/index.ts
  packages/service/src/router.tsx
  pnpm-lock.yaml
Labels: ✨ feat

#79 feat(CLAP-67): 당첨자 정보 입력 폼 만들기
  packages/core/src/types/orderEvent/index.ts
  packages/service/src/apis/orderEvent/apiPostOrderEventApply.ts
  packages/service/src/apis/orderEvent/type.ts
  packages/service/src/common/components/ModalContainer/content/modalContent.tsx
  packages/service/src/common/utils/formatter.ts
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizInput/NQuizInput.tsx
  packages/service/src/constants/routes.ts
  packages/service/src/pages/NQuizEventWinnerApply/NQuizEventWinnerApply.css.ts
  packages/service/src/pages/NQuizEventWinnerApply/NQuizEventWinnerApply.tsx
  packages/service/src/pages/NQuizEventWinnerApply/index.ts
  packages/service/src/pages/index.ts
  packages/service/src/router.tsx
Labels: ✨ feat

#80 Feat(CLAP-141): 응모 완료 페이지
  packages/service/src/Demo/pages/ButtonDemoPage.tsx
  packages/service/src/apis/expectation/apiPostExpectation.ts
  packages/service/src/apis/link/apiGetMyShareLink.ts
  packages/service/src/apis/lottery/apiGetLotteryStatus.ts
  packages/service/src/common/components/ClipBoardButton/ClipBoardButton.tsx
  packages/service/src/components/main/EventPeriod/Timer/Timer.css.ts
  packages/service/src/constants/routes.ts
  packages/service/src/index.tsx
  packages/service/src/pages/LotteryApplyFinish/LotteryApplyFinish.css.ts
  packages/service/src/pages/LotteryApplyFinish/LotteryApplyFinish.tsx
  packages/service/src/pages/LotteryApplyFinish/index.ts
  packages/service/src/pages/PartsPick/PartsPick.tsx
  packages/service/src/router.tsx
Labels: ✨ feat

#81 chore: 공유링크페이지 디자인수정, useAuth 구조 변경, handleTokenError 함수 추가
  packages/core/src/hooks/useAuth.ts
  packages/service/src/components/share/PartsTab/PartsWrap.css.ts
  packages/service/src/pages/PartsCollection/PartsCollection.tsx
Labels: 🍉 chore

#84 feat(CLAP-153): 퀴즈 Status 별 예외처리
  packages/service/src/components/nQuizEvent/NQuizReward/NQuizReward.css.ts
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizAlternativeBody/NQuizAlternativeBody.css.ts
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizAlternativeBody/NQuizAlternativeBody.tsx
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizInput/NQuizInput.tsx
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizSection.css.ts
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizSection.tsx
  packages/service/src/constants/quizContents.ts
  packages/service/src/pages/NQuizEvent/NQuizEvent.tsx
Labels: ✨ feat

#86 chore(CLAP-156): 이벤트 기간 수정
  packages/service/src/components/main/EventPeriod/EventPeriod.tsx
  packages/service/src/components/nQuizEvent/NQuizTitle/NQuizTitle.tsx
  packages/service/src/pages/PickEvent/PickEvent.tsx
Labels: 🍉 chore

#85 feat(CLAP-155): 메인페이지 기대평 API 구현
  packages/service/src/apis/expectation/apiGetExpectation.ts
  packages/service/src/apis/expectation/type.ts
  packages/service/src/common/components/Marquee/Marquee.css.ts
  packages/service/src/common/components/Marquee/Marquee.tsx
  packages/service/src/components/main/Expectation/Expectations.tsx
  packages/service/src/pages/NQuizEvent/NQuizEvent.tsx
Labels: ✨ feat

#87 hotfix: 리워드 이미지 비율 수정, 기대평 쿼리키 중복 수정, 대체 퀴즈 노출 수정
  packages/service/src/components/main/Expectation/Expectations.tsx
  packages/service/src/components/nQuizEvent/NQuizReward/NQuizReward.css.ts
  packages/service/src/pages/NQuizEvent/NQuizEvent.tsx
Labels: 🔧 hotfix

#88 feat(CLAP-157): 파츠페이지 레이아웃 수정
  packages/service/src/components/partsCollection/CustomCard/CustomCard.css.ts
  packages/service/src/components/partsCollection/PartsTab/PartsCard/PartsCard.css.ts
  packages/service/src/components/partsCollection/PartsTab/PartsTab.css.ts
  packages/service/src/pages/PartsCollection/PartsCollection.css.ts
  packages/service/src/pages/PartsCollection/PartsCollection.tsx
Labels: ✨ feat

#90 feat(CLAP-153): 어드민 로그인 처리 추가
  packages/admin/src/App.tsx
  packages/admin/src/apis/auth/apiGetAdminAuth.ts
  packages/admin/src/common/components/GlobalNavigationBar/GlobalNavigationBar.tsx
  packages/admin/src/pages/Error/Error.css.ts
  packages/admin/src/pages/Error/Error.tsx
  packages/admin/src/pages/Error/index.ts
  packages/admin/src/router.tsx
Labels: ✨ feat

#91 feat(CLAP-149): 메인페이지 이벤트바로가기 버튼 클릭 시 스크롤 이동
  packages/service/package.json
  packages/service/src/components/main/Banner/Banner.tsx
  packages/service/src/pages/Main/Main.tsx
  pnpm-lock.yaml
Labels: ✨ feat

#92 feat: 페이지 이동 시 스크롤 상단 고정
  packages/service/src/App.tsx
  packages/service/src/common/components/ScrollToTop/ScrollToTop.tsx
  packages/service/src/common/components/ScrollToTop/index.ts
  packages/service/src/index.tsx
Labels: ✨ feat

#93 feat(CLAP-158): 선착순 퀴즈 당첨자 입력폼 수정
  packages/service/src/apis/orderEvent/apiPostOrderEventApply.ts
  packages/service/src/common/components/Button/Button.css.ts
  packages/service/src/common/components/CheckBox/CheckBox.css.ts
  packages/service/src/common/components/ModalContainer/content/modalContent.tsx
  packages/service/src/common/utils/regex.ts
  packages/service/src/components/nQuizEvent/NQuizReward/NQuizReward.css.ts
  packages/service/src/pages/NQuizEventWinnerApply/NQuizEventWinnerApply.css.ts
  packages/service/src/pages/NQuizEventWinnerApply/NQuizEventWinnerApply.tsx
Labels: ✨ feat

#95 feat(CLAP-160): 파츠뽑기 카드 하단에 이름 노출
  packages/service/src/components/partsPick/PartsCard/PartsCard.tsx
  packages/service/src/pages/PartsPick/PartsPick.css.ts
  packages/service/src/pages/PartsPick/PartsPick.tsx
Labels: ✨ feat

#96 chore(CLAP-159): 컴포넌트 크기 축소
  packages/service/src/components/main/Banner/Banner.tsx
  packages/service/src/components/main/EventCard/EventCard.css.ts
  packages/service/src/components/main/EventCard/EventCard.tsx
  packages/service/src/components/main/EventPeriod/EventPeriod.css.ts
  packages/service/src/components/main/EventPeriod/Timer/Timer.css.ts
  packages/service/src/components/newCar/NewCarInfo/NewCarInfo.css.ts
  packages/service/src/components/newCar/TracingCar/TracingCar.css.ts
  packages/service/src/components/pickEvent/JoinInfo/JoinInfo.css.ts
  packages/service/src/components/pickEvent/PrizeContainer/PrizeContainer.css.ts
  packages/service/src/components/pickEvent/PrizeContainer/PrizeContainer.tsx
  packages/service/src/components/pickEvent/PrizeContainer/PrizeItem/PrizeItem.css.ts
  packages/service/src/components/pickEvent/PrizeContainer/PrizeItem/PrizeItem.tsx
  packages/service/src/constants/breakpoints.ts
  packages/service/src/pages/Main/Main.css.ts
  packages/service/src/pages/PickEvent/PickEvent.css.ts
  packages/service/src/pages/PickEvent/PickEvent.tsx
Labels: 🍉 chore

#97 feat(CLAP-145): 비로그인 유저 예외처리
  packages/service/src/App.tsx
  packages/service/src/apis/partsEvent/apiGetPartsRemain.ts
  packages/service/src/pages/Error/Error.css.ts
  packages/service/src/pages/Error/Error.tsx
  packages/service/src/pages/LotteryApplyFinish/LotteryApplyFinish.tsx
  packages/service/src/pages/LotteryApplyInfo/LotteryApplyInfo.tsx
  packages/service/src/pages/PartsCollection/PartsCollection.tsx
  packages/service/src/pages/PartsPick/PartsPick.tsx
  packages/service/src/pages/PickEvent/PickEvent.css.ts
  packages/service/src/pages/PickEvent/PickEvent.tsx
Labels: ✨ feat

#98 feat(CLAP-163): 파츠뽑기 클릭 유도 UI 구현
  packages/service/src/components/ClickInduceIcon/ClickInduceIcon.tsx
  packages/service/src/components/ClickInduceIcon/index.ts
  packages/service/src/components/partsPick/PartsCard/PartsCard.tsx
  packages/service/src/pages/PartsPick/PartsPick.tsx
Labels: ✨ feat

#99 feat(CLAP-164): 파츠 컬렉션 커스텀카드 호버 시 파츠정보 노출
  packages/service/src/components/partsCollection/CustomCard/CustomCard.css.ts
  packages/service/src/components/partsCollection/CustomCard/CustomCard.tsx
  packages/service/src/components/partsCollection/PinContainer/Pin/Pin.css.ts
  packages/service/src/components/partsCollection/PinContainer/Pin/Pin.tsx
  packages/service/src/components/partsCollection/PinContainer/Pin/WaveCircle/WaveCircle.css.ts
  packages/service/src/components/partsCollection/PinContainer/Pin/WaveCircle/WaveCircle.tsx
  packages/service/src/components/partsCollection/PinContainer/Pin/WaveCircle/index.ts
  packages/service/src/components/partsCollection/PinContainer/Pin/index.ts
  packages/service/src/components/partsCollection/PinContainer/PinContainer.css.ts
  packages/service/src/components/partsCollection/PinContainer/PinContainer.tsx
  packages/service/src/components/partsCollection/PinContainer/index.ts
  packages/service/src/pages/PartsCollection/PartsCollection.css.ts
  packages/service/src/pages/PartsCollection/PartsCollection.tsx
Labels: ✨ feat

#100 hotfix: 호환성이슈 해결 및 퀴즈노출 이슈 해결
  packages/admin/public/fonts/pretendard/Pretendard-Bold.woff
  packages/admin/public/fonts/pretendard/Pretendard-Bold.woff2
  packages/admin/public/fonts/pretendard/Pretendard-Medium.woff
  packages/admin/public/fonts/pretendard/Pretendard-Medium.woff2
  packages/admin/public/fonts/pretendard/Pretendard-SemiBold.woff
  packages/admin/public/fonts/pretendard/Pretendard-SemiBold.woff2
  packages/core/src/theme/globalStyles.ts
  packages/service/public/fonts/pretendard/Pretendard-Bold.woff
  packages/service/public/fonts/pretendard/Pretendard-Bold.woff2
  packages/service/public/fonts/pretendard/Pretendard-Medium.woff
  packages/service/public/fonts/pretendard/Pretendard-Medium.woff2
  packages/service/public/fonts/pretendard/Pretendard-SemiBold.woff
  packages/service/public/fonts/pretendard/Pretendard-SemiBold.woff2
  packages/service/src/components/main/EventPeriod/EventPeriod.tsx
  packages/service/src/pages/NQuizEvent/NQuizEvent.tsx
Labels: 🔧 hotfix

#101 feat(CLAP-161): 기대평 나중에 쓸 수 있도록 수정
  packages/service/src/apis/expectation/apiGetCheckExpectation.ts
  packages/service/src/apis/expectation/type.ts
  packages/service/src/pages/LotteryApplyFinish/LotteryApplyFinish.tsx
  packages/service/src/pages/PartsPick/PartsPick.tsx
Labels: ✨ feat

#102 fix(CLAP-166): 카드뽑기 횟수가 없는 경우에도 뽑히는 이슈
  packages/service/src/common/components/ModalContainer/content/modalContent.tsx
  packages/service/src/components/partsPick/PartsCard/PartsCard.tsx
  packages/service/src/pages/PartsPick/PartsPick.tsx
Labels: 🛠️ fix

#104 hotfix: conflict 수정
  packages/service/src/pages/PartsPick/PartsPick.tsx
Labels: 🔧 hotfix

#105 feat(CLAP-167): 유효하지 않은 URL로 접근 시 메인페이지로 리다이렉트
  packages/service/src/apis/partsEvent/apiGetSharedParts.ts
  packages/service/src/constants/routes.ts
  packages/service/src/router.tsx
Labels: ✨ feat

#106 fix(CLAP-151): 파츠뽑기 API에 `credentials` 속성 추가
  packages/service/src/apis/partsEvent/apiPostParts.ts
Labels: 🛠️ fix

#107 fix(CLAP-151): credentials 속성 위치 수정
  packages/service/src/apis/partsEvent/apiPostParts.ts
Labels: 🛠️ fix

#108 feat(CLAP-169): 로그아웃 시 새로고침
  packages/core/src/hooks/useAuth.ts
Labels: ✨ feat

#109 chore(CLAP-170): 모달 내용 다듬기
  packages/admin/src/pages/orderEvent/OrderEventGeneration/OrderEventGeneration.tsx
  packages/admin/src/pages/orderEvent/OrderEventManagement/OrderEventManagement.tsx
  packages/admin/src/pages/partsEvent/PartsEventGeneration/PartsEventGeneration.tsx
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/GlobalNavs.tsx
  packages/service/src/pages/LotteryApplyFinish/LotteryApplyFinish.tsx
Labels: 🍉 chore

#110 feat(CLAP-171): 기대평 이미 제출한 유저 기대평 입력란 숨기기
  packages/service/src/pages/LotteryApplyFinish/LotteryApplyFinish.css.ts
  packages/service/src/pages/LotteryApplyFinish/LotteryApplyFinish.tsx
Labels: ✨ feat

#111 fix(CLAP-172): Footer에 `지금바로뽑기` 버튼 안 겹치게 수정
  packages/service/src/pages/PickEvent/PickEvent.css.ts
  packages/service/src/pages/PickEvent/PickEvent.tsx
Labels: ✨ feat

#112 fix(CLAP-168): 레이아웃 수정
  packages/service/src/common/components/Footer/Footer.css.ts
  packages/service/src/components/nQuizEvent/NQuizReward/NQuizReward.css.ts
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizSection.css.ts
  packages/service/src/components/partsCollection/CustomCard/CustomCard.tsx
  packages/service/src/components/partsCollection/PartsTab/PartsTab.css.ts
  packages/service/src/components/share/CustomCard/CustomCard.css.ts
  packages/service/src/components/share/CustomCard/CustomCard.tsx
  packages/service/src/components/share/CustomCard/index.ts
  packages/service/src/components/share/PartsTab/PartsCard/PartsCard.css.ts
  packages/service/src/components/share/PartsTab/PartsCard/PartsCard.tsx
  packages/service/src/components/share/PartsTab/PartsWrap.css.ts
  packages/service/src/components/share/PartsTab/PartsWrap.tsx
  packages/service/src/components/share/index.ts
  packages/service/src/constants/breakpoints.ts
  packages/service/src/pages/LotteryApplyInfo/LotteryApplyInfo.css.ts
  packages/service/src/pages/LotteryApplyInfo/LotteryApplyInfo.tsx
  packages/service/src/pages/NQuizEvent/NQuizEvent.css.ts
  packages/service/src/pages/NQuizEventWinnerApply/NQuizEventWinnerApply.css.ts
  packages/service/src/pages/PartsCollection/PartsCollection.css.ts
  packages/service/src/pages/Share/Share.css.ts
  packages/service/src/pages/Share/Share.tsx
Labels: 🛠️ fix

#113 fix(CLAP-151): 공유링크로 들어간 유저가 로그인 시 뽑기권 증가 안되는 이슈
  packages/core/src/apis/login/apiGetLoginValid.ts
  packages/core/src/hooks/useAuth.ts
  packages/service/src/apis/partsEvent/apiPostParts.ts
Labels: ✨ feat

#114 feat(CLAP-175): 어드민 미구현 기능 추가
  packages/admin/public/images/modal/pending.gif
  packages/admin/src/apis/partsEvent/apiGetLotteries.ts
  packages/admin/src/apis/partsEvent/apiGetPartsWinner.ts
  packages/admin/src/apis/partsEvent/apiPostLotteries.ts
  packages/admin/src/apis/partsEvent/apiPostLotteriesCheckStatus.ts
  packages/admin/src/apis/partsEvent/apiPostPartsEvent.ts
  packages/admin/src/apis/partsEvent/apiPostPartsEventWinner.ts
  packages/admin/src/apis/partsEvent/apiPostPartsWinnerCheckStatus.ts
  packages/admin/src/apis/partsEvent/type.ts
  packages/admin/src/common/components/ModalContainer/ModalContainer.tsx
  packages/admin/src/common/components/ModalContainer/modal/PendingModal/PendingModal.css.ts
  packages/admin/src/common/components/ModalContainer/modal/PendingModal/PendingModal.tsx
  packages/admin/src/common/components/ModalContainer/modal/PendingModal/index.ts
  packages/admin/src/common/components/ModalContainer/modal/index.ts
  packages/admin/src/components/partsEvent/WinnerDataGrid/MainEventWinnerDataGrid.tsx
  packages/admin/src/components/partsEvent/WinnerDataGrid/MiniatureEventWinnerDataGrid.tsx
  packages/admin/src/components/partsEvent/WinnerDataGrid/WinnerDataGrid.tsx
  packages/admin/src/components/partsEvent/WinnerDataGrid/index.ts
  packages/admin/src/pages/partsEvent/PartsEventDraw/PartsEventDraw.tsx
  packages/admin/src/pages/partsEvent/PartsEventGeneration/PartsEventGeneration.tsx
  packages/admin/src/pages/partsEvent/PartsEventWinnerManagement/PartsEventWinnerManagement.tsx
Labels: ✨ feat

#116 fix(CLAP-165): 트레이싱카 경로 오류 수정
  packages/service/src/components/newCar/NewCarInfo/NewCarInfo.tsx
  packages/service/src/components/newCar/TracingCar/TracingCar.css.ts
  packages/service/src/components/newCar/TracingCar/TracingCar.tsx
Labels: 🛠️ fix

#117 hotfix: 미사용 코드 제거
  packages/admin/src/components/partsEvent/ExpectationDataGrid/ExpectationDataGrid.tsx
  packages/admin/src/pages/orderEvent/OrderEventManagement/OrderEventManagement.tsx
Labels: 🔧 hotfix

#119 hotfix: 배경 이미지 경로 수정 및 폰트 수정
  packages/core/src/theme/globalStyles.ts
  packages/core/src/theme/theme.ts
  packages/service/public/fonts/pretendard/Pretendard-Bold.otf
  packages/service/public/fonts/pretendard/Pretendard-Bold.woff
  packages/service/public/fonts/pretendard/Pretendard-Medium.otf
  packages/service/public/fonts/pretendard/Pretendard-Medium.woff
  packages/service/public/fonts/pretendard/Pretendard-SemiBold.otf
  packages/service/public/fonts/pretendard/Pretendard-SemiBold.woff
  packages/service/src/common/components/Button/Button.css.ts
  packages/service/src/common/components/ClipBoardButton/ClipBoardButton.css.ts
  packages/service/src/components/main/EventCard/EventCard.css.ts
  packages/service/src/pages/Error/Error.css.ts
  packages/service/src/pages/Loading/Loading.css.ts
  packages/service/src/pages/LotteryApplyFinish/LotteryApplyFinish.css.ts
  packages/service/src/pages/LotteryApplyInfo/LotteryApplyInfo.css.ts
  packages/service/src/pages/Main/Main.css.ts
  packages/service/src/pages/PartsCollection/PartsCollection.css.ts
  packages/service/src/pages/PartsPick/PartsPick.css.ts
  packages/service/src/pages/PickEvent/PickEvent.css.ts
  packages/service/src/pages/Share/Share.css.ts
Labels: 🔧 hotfix

#120 chore: 오타 수정
  packages/service/src/common/components/Button/Button.css.ts
Labels: 🔧 hotfix

#123 hotfix: 아이폰에서 카드 뽑기 애니메이션 미작동 및 파츠컬렉션 안내 아이콘
  packages/service/public/images/parts/holo.png
  packages/service/public/images/parts/sparkles.gif
  packages/service/src/common/components/ClickInduceIcon/ClickInduceIcon.tsx
  packages/service/src/common/components/ClickInduceIcon/index.ts
  packages/service/src/components/partsCollection/PinContainer/PinContainer.tsx
  packages/service/src/components/partsPick/PartsCard/PartsCard.css.ts
  packages/service/src/components/partsPick/PartsCard/PartsCard.tsx
  packages/service/src/pages/PartsPick/PartsPick.tsx
Labels: 🔧 hotfix

#121 hotfix: 폰트크기 축소, 카드 캐러셀 크기 조절
  packages/service/src/components/main/EventCard/EventCard.css.ts
  packages/service/src/components/pickEvent/CardCarousel/CardCarousel.tsx
  packages/service/src/pages/Error/Error.css.ts
  packages/service/src/pages/Error/Error.tsx
  packages/service/src/pages/LotteryApplyInfo/LotteryApplyInfo.css.ts
Labels: 🔧 hotfix

#122 fix(CLAP-176): 로그인 만료 시 타이머 음수 되는 이슈 해결, 로그인 연장 클릭 시 확인 모달 띄우기
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/ExpirationTimer/ExpirationTimer.tsx
Labels: 🛠️ fix

#124 chore(CLAP-179): 스크롤바 디자인 수정
  packages/service/src/index.css
Labels: 🍉 chore

#125 feat(CLAP-178): 보유중인 파츠가 없을 경우 안내 문구 출력
  packages/service/src/components/partsCollection/PartsTab/PartsTab.css.ts
  packages/service/src/components/partsCollection/PartsTab/PartsTab.tsx
Labels: ✨ feat

#126 fix(CLAP-177): `ErrorBoundary` 에서 뒤로가기 안 되던 이슈 해결
  packages/service/src/pages/Error/Error.tsx
Labels: 🛠️ fix

#127 feat(CLAP-180): flow 재조정 및 기기별 애니메이션 구분
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/GlobalNavs.tsx
  packages/service/src/common/utils/deviceChecker.ts
  packages/service/src/components/partsPick/PartsCard/PartsCard.css.ts
  packages/service/src/components/partsPick/PartsCard/PartsCard.tsx
  packages/service/src/constants/routes.ts
  packages/service/src/pages/LotteryApplyFinish/LotteryApplyFinish.css.ts
  packages/service/src/pages/LotteryApplyFinish/LotteryApplyFinish.tsx
  packages/service/src/pages/LotteryApplyFinish/index.ts
  packages/service/src/pages/LotteryApplyInfo/LotteryApplyInfo.css.ts
  packages/service/src/pages/LotteryApplyInfo/LotteryApplyInfo.tsx
  packages/service/src/pages/PartsCollection/PartsCollection.css.ts
  packages/service/src/pages/PartsCollection/PartsCollection.tsx
  packages/service/src/pages/PartsPick/PartsPick.css.ts
  packages/service/src/pages/PartsPick/PartsPick.tsx
  packages/service/src/router.tsx
Labels: ✨ feat

#128 feat(CLAP-181): 모바일뷰에서 핀컨테이너 터치이벤트 추가
  packages/service/src/apis/partsEvent/apiPatchMyParts.ts
  packages/service/src/components/partsCollection/PinContainer/Pin/Pin.css.ts
  packages/service/src/components/partsCollection/PinContainer/Pin/Pin.tsx
  packages/service/src/components/partsCollection/PinContainer/PinContainer.tsx
Labels: ✨ feat

#129 hotfix: GNB 스타일링, 이미지 크기조절, 각종 UX 개선
  packages/service/src/common/components/CheckBox/CheckBox.css.ts
  packages/service/src/common/components/CheckBox/CheckBox.tsx
  packages/service/src/common/components/ClickInduceIcon/ClickInduceIcon.tsx
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/ExpirationTimer/ExpirationTimer.css.ts
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/ExpirationTimer/ExpirationTimer.tsx
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/GlobalNavs.css.ts
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/GlobalNavs.tsx
  packages/service/src/components/main/Banner/Banner.css.ts
  packages/service/src/components/main/EventPeriod/EventPeriod.css.ts
  packages/service/src/components/pickEvent/CardCarousel/CardCarousel.css.ts
  packages/service/src/components/pickEvent/CardCarousel/CardCarousel.tsx
  packages/service/src/pages/Main/Main.tsx
  packages/service/src/pages/NewCar/NewCar.css.ts
  packages/service/src/pages/NewCar/NewCar.tsx
Labels: 🔧 hotfix

#130 chore(CLAP-182): 미사용 코드 제거 및 컨벤션 통일
  packages/service/src/App.tsx
  packages/service/src/Demo/pages/AuthDemoPage.tsx
  packages/service/src/Demo/pages/ButtonDemoPage.tsx
  packages/service/src/Demo/pages/DemoPage.tsx
  packages/service/src/Demo/pages/MarqueeDemoPage.tsx
  packages/service/src/Demo/pages/ModalDemoPage.tsx
  packages/service/src/Demo/pages/RotateDemoPage.tsx
  packages/service/src/Demo/pages/ScrollDemoPage.tsx
  packages/service/src/Demo/pages/ScrollTextPage.tsx
  packages/service/src/apis/expectation/index.ts
  packages/service/src/common/components/AssetLoaderOverlay/AssetWrapper.tsx
  packages/service/src/common/components/AssetLoaderOverlay/Overlay.css.ts
  packages/service/src/common/components/AssetLoaderOverlay/Overlay.tsx
  packages/service/src/common/components/BorderBeam/BorderBeam.tsx
  packages/service/src/common/components/BorderBeam/index.ts
  packages/service/src/common/components/Button/Button.tsx
  packages/service/src/common/components/CheckBox/CheckBox.tsx
  packages/service/src/common/components/ClipBoardButton/ClipBoardButton.tsx
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavigationBar.tsx
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/GlobalNavs.tsx
  packages/service/src/common/components/Marquee/Marquee.tsx
  packages/service/src/common/components/Marquee/index.ts
  packages/service/src/common/components/Marquee/index.tsx
  packages/service/src/common/components/ModalContainer/modal/AlertModal/AlertModal.tsx
  packages/service/src/common/components/ModalContainer/modal/ConfirmModal/ConfirmModal.tsx
  packages/service/src/common/components/ModalContainer/modal/DescriptionModal/DescriptionModal.tsx
  packages/service/src/common/components/ModalContainer/modal/GoolgleLoginModal/GoogleLoginModal.tsx
  packages/service/src/common/components/ModalContainer/modal/NavigateModal/NavigateModal.tsx
  packages/service/src/common/components/ModalContainer/modal/PendingModal/PendingModal.tsx
  packages/service/src/common/components/VirtualScrollBar/VirtualScrollBar.css.ts
  packages/service/src/common/components/VirtualScrollBar/VirtualScrollBar.tsx
  packages/service/src/common/components/VirtualScrollBar/index.ts
  packages/service/src/common/contexts/AssetLoaderContext.ts
  packages/service/src/common/providers/AssetLoaderContextProvider.tsx
  packages/service/src/components/Game/Game.tsx
  packages/service/src/components/Game/index.ts
  packages/service/src/components/main/Expectation/Expectations.tsx
  packages/service/src/components/nQuizEvent/NQuizReward/NQuizReward.tsx
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizAlternativeBody/NQuizAlternativeBody.tsx
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizHeader/NQuizHeader.tsx
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizInput/NQuizInput.tsx
  packages/service/src/components/nQuizEvent/NQuizSection/NQuizSection.tsx
  packages/service/src/components/nQuizEvent/NQuizTitle/NQuizTitle.tsx
  packages/service/src/components/newCar/TracingCar/TracingCar.tsx
  packages/service/src/components/partsPick/PickTitle/PickTitle.tsx
  packages/service/src/constants/routes.ts
  packages/service/src/index.tsx
  packages/service/src/pages/Error/Error.tsx
  packages/service/src/pages/LotteryApplyInfo/LotteryApplyInfo.tsx
  packages/service/src/pages/NQuizEvent/NQuizEvent.tsx
  packages/service/src/pages/NQuizEventWinnerApply/NQuizEventWinnerApply.tsx
  packages/service/src/pages/PartsPick/PartsPick.tsx
  packages/service/src/pages/index.ts
  packages/service/src/router.tsx
Labels: 🍉 chore

#131 fix(CLAP-183): 선착순 이벤트 기간 노출 이슈
  packages/service/src/common/utils/formatter.ts
  packages/service/src/components/nQuizEvent/NQuizTitle/NQuizTitle.tsx
  packages/service/src/pages/NQuizEvent/NQuizEvent.tsx
Labels: 🛠️ fix

#132 refactor(CLAP-184): ModalContainer 리팩토링
  packages/core/src/contexts/ModalContext.ts
  packages/core/src/hooks/useModal.ts
  packages/core/src/providers/ModalProvider.tsx
  packages/service/src/common/components/ModalContainer/ModalContainer.tsx
Labels: ☘︎ refactor

#133 chore: og:title 변경
  packages/service/index.html
Labels: 🍉 chore

#134 hotfix: 아이폰에서 배너이미지가 화면에 꽉 차는 이슈
  packages/service/src/components/main/Banner/Banner.css.ts
  packages/service/src/pages/NewCar/NewCar.css.ts
Labels: 🔧 hotfix

#135 __hotfix: GNB의 `active된 link`의 스타일링에 breakPoint 수정
  packages/service/src/common/components/GlobalNavigationBar/GlobalNavs/GlobalNavs.css.ts
Labels: 🔧 hotfix
