Repository softeerbootcamp4th/Team5-WatermelonClap-FE, pull requests merged in 2024-07, with the labels that each got.

#4 feat(CLAP-30): 스크롤 텍스트 데모
  .gitignore
  packages/service/.env.example
  packages/service/src/Demo/pages/DemoPage.tsx
  packages/service/src/Demo/pages/ScrollTextPage.tsx
  packages/service/src/constants/routes.ts
  packages/service/src/router.tsx
Labels: ✨ feat

#7 fix(CLAP-41): service가 변경된 경우에만 service 관련 action 실행
  .github/workflows/fb-hosting-service-merge.yml
  .github/workflows/fb-hosting-service-pull-request.yml
Labels: 🧪 test

#9 feat(CLAP-33): 이미지 로드 스크린
  packages/service/src/Main/pages/MainPage.tsx
  packages/service/src/common/components/AssetLoaderOverlay/AssetWrapper.tsx
  packages/service/src/common/components/AssetLoaderOverlay/Overlay.css.ts
  packages/service/src/common/components/AssetLoaderOverlay/Overlay.tsx
  packages/service/src/common/contexts/AssetLoaderContext.ts
  packages/service/src/common/providers/AssetLoaderContextProvider.tsx
  packages/service/src/router.tsx
  pnpm-lock.yaml
Labels: ✨ feat

#25 chore(CLAP-117): 폴더구조 정리
  packages/service/src/components/Game/Game.tsx
  packages/service/src/components/Game/index.ts
  packages/service/src/components/MainBanner/MainBanner.css.ts
  packages/service/src/components/MainBanner/MainBanner.tsx
  packages/service/src/components/MainBanner/MainBannerContent.tsx
  packages/service/src/components/MainBanner/index.tsx
  packages/service/src/pages/MainPage.tsx
  packages/service/src/router.tsx
Labels: 🍉 chore

#26 feat(CLAP-71): 디자인 토큰 정의
  packages/admin/index.html
  packages/admin/src/index.tsx
  packages/admin/src/pages/MainPage.tsx
  packages/admin/src/router.tsx
  packages/core/package.json
  packages/core/public/fonts/pretendard/Pretendard-Bold.woff2
  packages/core/public/fonts/pretendard/Pretendard-Medium.woff2
  packages/core/public/fonts/pretendard/Pretendard-SemiBold.woff2
  packages/core/public/fonts/pyeongChang/PyeongChang-Bold.otf
  packages/core/public/fonts/pyeongChang/PyeongChang-Regular.otf
  packages/core/public/fonts/pyeongChangPeace/PyeongChangPeace-Bold.otf
  packages/core/public/fonts/pyeongChangPeace/PyeongChangPeace-Light.otf
  packages/core/src/index.ts
  packages/core/src/theme/baseStyles.ts
  packages/core/src/theme/globalStyles.ts
  packages/core/src/theme/index.ts
  packages/core/src/theme/theme.ts
  packages/service/index.html
  packages/service/src/index.tsx
  packages/service/src/pages/MainPage.tsx
  pnpm-lock.yaml
Labels: ✨ feat

#27 fix: core에 있던 font 적용 안되는 이슈 해결
  packages/core/src/fonts/pretendard/Pretendard-Bold.woff2
  packages/core/src/fonts/pretendard/Pretendard-Medium.woff2
  packages/core/src/fonts/pretendard/Pretendard-SemiBold.woff2
  packages/core/src/fonts/pyeongChang/PyeongChang-Bold.otf
  packages/core/src/fonts/pyeongChang/PyeongChang-Regular.otf
  packages/core/src/fonts/pyeongChangPeace/PyeongChangPeace-Bold.otf
  packages/core/src/fonts/pyeongChangPeace/PyeongChangPeace-Light.otf
  packages/core/src/index.css
Labels: 🛠️ fix

#28 fix(CLAP-80): font 파일 위치 변경
  packages/core/src/aeests/fonts/pretendard/Pretendard-Bold.woff2
  packages/core/src/aeests/fonts/pretendard/Pretendard-Medium.woff2
  packages/core/src/aeests/fonts/pretendard/Pretendard-SemiBold.woff2
  packages/core/src/aeests/fonts/pyeongChang/PyeongChang-Bold.otf
  packages/core/src/aeests/fonts/pyeongChang/PyeongChang-Regular.otf
  packages/core/src/aeests/fonts/pyeongChangPeace/PyeongChangPeace-Bold.otf
  packages/core/src/aeests/fonts/pyeongChangPeace/PyeongChangPeace-Light.otf
  packages/core/src/theme/globalStyles.ts
  packages/core/src/theme/index.ts
  packages/service/src/index.css
  packages/service/src/index.tsx
  packages/service/src/pages/Main.tsx
  packages/service/src/router.tsx
Labels: 🛠️ fix

#29 fix: assets 폴더명 오타
  packages/core/src/assets/fonts/pretendard/Pretendard-Bold.woff2
  packages/core/src/assets/fonts/pretendard/Pretendard-Medium.woff2
  packages/core/src/assets/fonts/pretendard/Pretendard-SemiBold.woff2
  packages/core/src/assets/fonts/pyeongChang/PyeongChang-Bold.otf
  packages/core/src/assets/fonts/pyeongChang/PyeongChang-Regular.otf
  packages/core/src/assets/fonts/pyeongChangPeace/PyeongChangPeace-Bold.otf
  packages/core/src/assets/fonts/pyeongChangPeace/PyeongChangPeace-Light.otf
  packages/service/src/pages/Main.tsx
Labels: 🛠️ fix

#30 fix: font 적용 안되는 이슈해결
  packages/core/src/index.css
  packages/core/src/theme/globalStyles.ts
  packages/core/src/theme/index.ts
  packages/service/src/assets/fonts/pretendard/Pretendard-Bold.woff2
  packages/service/src/assets/fonts/pretendard/Pretendard-Medium.woff2
  packages/service/src/assets/fonts/pretendard/Pretendard-SemiBold.woff2
  packages/service/src/assets/fonts/pyeongChang/PyeongChang-Bold.otf
  packages/service/src/assets/fonts/pyeongChang/PyeongChang-Regular.otf
  packages/service/src/assets/fonts/pyeongChangPeace/PyeongChangPeace-Bold.otf
  packages/service/src/assets/fonts/pyeongChangPeace/PyeongChangPeace-Light.otf
  packages/service/src/index.css
  packages/service/src/index.tsx
  packages/service/src/pages/Main.tsx
Labels: 🛠️ fix

#34 feat(CLAP-75): Footer 컴포넌트 구현
  packages/service/src/App.tsx
  packages/service/src/common/components/Footer/Footer.css.ts
  packages/service/src/common/components/Footer/Footer.tsx
  packages/service/src/common/components/Footer/index.ts
  packages/service/src/components/main/Banner/Banner.tsx
Labels: ✨ feat
